### ISSUE TITLE
Change privacy settings in Edge

### ISSUE THREAD

**Issue by hahndorf** [hahndorf/Set-Privacy#6]
> More Actions > Settings > View advanced settings. Enable Do Not Track requests and disable search suggestions, page prediction and SmartScreen filter. Make sure that Cortana is switched off too.

**Comment by urras** [comment]
After some fooling around in the registry, here's what I found:

DNT settings are in `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\Main`, as `DoNotTrack`

Search suggestions are in `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\User\Default\SearchScopes`, as `ShowSearchSuggestionsGlobal`

Page prediction is in `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\FlipAhead`, as `FPEnabled`

Smartscreen is in `HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\PhishingFilter`, as `EnabledV9`.

As for Cortana, once "speech, typing and inking input" is disabled, Cortana becomes disabled (or at least that's what I observed). I'm not sure that there's an an actual key to disable Cortana entirely. I'd recommend that you use a tool like Regshot to track changes to the registry, since trying to track them manually is a nightmare.

**Comment by hahndorf** [comment]
@urras - Thanks, for this. I'm using Process Monitor to find out about the keys, that works pretty well. I added those 4 settings to the script.
